# flake8: noqa

"""
    Owlery API

    Owlery provides a web API for an [OWL API](https://owlapi.sourceforge.net)-based reasoner containing a
    configurable set of ontologies (a \"knowledgebase\").

    The version of the OpenAPI document: 1.0.0
    Contact: balhoff@renci.org
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from owlery_client.api_client import ApiClient

# the experts suggest not doing this, because it can be a heavy lift.
# But that's not a problem for this API, which is trivial.
import owlery_client.api
import owlery_client.apis
import owlery_client.model
import owlery_client.models


# import Configuration
from owlery_client.configuration import Configuration

# import exceptions
from owlery_client.exceptions import OpenApiException
from owlery_client.exceptions import ApiAttributeError
from owlery_client.exceptions import ApiTypeError
from owlery_client.exceptions import ApiValueError
from owlery_client.exceptions import ApiKeyError
from owlery_client.exceptions import ApiException
